# Compose file generated automatically

version: '3.6'

services:
  simplerisk:
    environment:
    - FIRST_TIME_SETUP=1
    - FIRST_TIME_SETUP_PASS=t4zuiINWBa7lhBK-kSzfp
    - SIMPLERISK_DB_HOSTNAME=mariadb
    image: simplerisk/simplerisk-minimal:20220823-001
    ports:
    - "80:80"
    - "443:443"

  mariadb:
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
    - MYSQL_ROOT_PASSWORD=t4zuiINWBa7lhBK-kSzfp
    image: mariadb:10.7

  smtp:
    image: namshi/smtp
