name: Push resulting image to DockerHub

on:
  workflow_call:
    inputs:
      context_path:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string
      os_version:
        required: true
        type: string
      main_image:
        required: false
        default: false
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_name }}

    - name: Build and push main Docker image
      if: ${{ inputs.main_image == 'true' }}
      id: build-and-push-main
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile_path }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ inputs.image_name }}
          ${{ inputs.image_name }}:${{ inputs.version }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push specific Docker image
      id: build-and-push-spec
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile_path }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ inputs.image_name }}:${{ inputs.version }}-${{ inputs.os_version }}
        labels: ${{ steps.meta.outputs.labels }}
 
